language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t salahkmt/complex-fib -f ./client/Dockerfile.dev ./client/

script : 
  - docker run -e CI=true salahkmt/complex-fib npm run test

after_sucess:
  - docker build -t salahkmt/complex-fib-client ./client
  - docker build -t salahkmt/complex-fib-nginx ./nginx
  - docker build -t salahkmt/complex-fib-server ./server
  - docker build -t salahkmt/complex-fib-worker ./worker
# Log to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push docker images into Docker Hub  
  - docker push salahkmt/complex-fib-client
  - docker push salahkmt/complex-fib-nginx 
  - docker push salahkmt/complex-fib-server
  - docker push salahkmt/complex-fib-worker

deploy : 
  provider : elasticbeanstalk
  region : "us-east-2"
  app : "complex-fibonacci"
  env : "Complexfibonacci-env-1"
  bucket_name : "elasticbeanstalk-us-east-2-970866749731"
  bucket_path : "complex-fibonacci"
  on : 
    branch : main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"